services:
  graphql: 
    container_name: graphile
    restart: always
    image: graphile
    build:
      context: ./graphql
    env_file:
      - ./.env
    networks:
      - ignition
    ports:
      - 5999:5999
    command: ["--connection", "${DATABASE_URL}", "--port", "5999", "--schema", "public", "--append-plugins", "@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,graphile-upsert-plugin", "--watch", "--allow-explain", "--enhance-graphiql", "--dynamic-json"]
  tsdb:
    container_name: tsdb
    restart: always
    image: 
networks:
  ignition:
    external: true
    name: ignition
